---
- name: Building disk layout
  include_tasks: "disk_creator.yaml"
  loop: "{{ ansible_local.disk_layout }}"

- name: Fail if bootstrapped and changes have been made
  assert:
    that: "disk_layout_changed == false"
    fail_msg: "This role run in check mode and expected no changes"
    success_msg: "Facts' layout matches host's layout"
  when: ansible_local.bootstrapped | default(false) and not ansible_check_mode
